### ISSUE TITLE
XRM-Server [AccessLevels] Convert from yaml to Model and DAO

### ISSUE THREAD

**Issue by M-griffin** [M-griffin/Oblivion2-XRM#164]
Instead of a config file, this should be stored in a table.
Also add fields for each level, Time Limit, Time Level, PCR, ul/dl limits etc..  
One login, if the users is in one of these levels it should update the users limits on their first logon of the day.

**Comment by M-griffin** [comment]
Existing Access Level Yaml was converted to new Protocol Yaml configuration.
Next Step, create new Access Level Dao.

**Comment by lmanuel** [comment]
Loving what I see man. :D

**Comment by M-griffin** [comment]
Thanks man!  It's coming along.. lots to do still.. 👍

**Comment by M-griffin** [comment]
This is completed per pull Request #171
